version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - .env

  web:
    build: .
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

  nginx:
    build: ./nginx/.
    volumes:
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  static_value:
  media_value:
