FROM python:3
WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONBUFFERED 1

RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip install -r requirements.txt

COPY ./entrypoint.prod.sh .
RUN chmod +x /app/entrypoint.prod.sh

COPY . .
ENTRYPOINT [ "/app/entrypoint.prod.sh" ]