version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile_prod
    expose:
      - 8000
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    ports:
      - 5433:5433
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env_db.prod

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: