name: CI

on: [push]

jobs:
  #job called build
  tests:
    name: test Ubuntu
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
      
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
          pip install -r requirements.txt
      - name: Test with flake8 and django tests
        run: python -m flake8
  
  build:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: u23375764
          password: 234895QqQ
      - name: Push to Docker Hub
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: u23375764/hello_docer
